# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e7fe10e43b6b0f1c0275d2ae675a2829b58092acfb4285d9c48b9f4c1dc805bd9e6736c6db560266964c5b98d753d141ddcda9dde2dba883791c5906bef61a

test:
  secret_key_base: bf75f53210fca669c35dcb3b4f7888c59f119499b0d6365b8b330bd0e6246353f15eec31c87bd74f9bcffaa30eab2443737d5f45f0551a79f7762bd7c120fef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
